### ISSUE TITLE
clearSelection() not exist

### ISSUE THREAD

**Issue by ahmed-asiri** [dbilgili/Custom-ReactJS-Dropdown-Components#25]
i cant find the clearSelection on the compnent

**Comment by dbilgili** [comment]
Hey,
It's hard to tell what is wrong without an example code, but did you pass a ref to the component as explained in [this](https://codesandbox.io/s/tender-ives-rp05n?file=/src/App.js) section?

You can find a working example [there](https://codesandbox.io/s/tender-ives-rp05n?file=/src/App.js).

**Comment by ahmed-asiri** [comment]
when i log the ref, i got all these functions:
![image](https://user-images.githubusercontent.com/52707654/106885891-4e800c00-66f4-11eb-8f62-55c6557e28ab.png)


but the clearSelection, is not exist with them, and also if i tried to invoked i got exception of (is not a function)

i installed the package before 12 days, do i need to update it?

**Comment by dbilgili** [comment]
`1.1.8` is the version this method was introduced in. So, if you're using an earlier version, updating should do the trick 👍🏻

**Comment by ahmed-asiri** [comment]
I was having the 1.1.7 version, 
it works now after updating to 1.1.9, 
thank you Biligili.
